import json

from sqlalchemy.orm import Session

from .models import Lesson

LESSON_SEED = [
    {
        "code": "ab6-greetings-1",
        "title": "Friendly Greetings",
        "subject": "speaking",
        "level": "Beginner",
        "age_band": "6-10",
        "order_index": 1,
        "description": "Say hello, introduce yourself, and ask simple questions.",
        "duration_minutes": 10,
        "xp_reward": 40,
        "content": {
            "explanation": "Use short polite phrases: Hello, My name is..., How are you?",
            "examples": ["Hello! My name is Mia.", "How are you today?", "Nice to meet you!"],
        },
    },
    {
        "code": "ab6-colors-1",
        "title": "Colors Around Us",
        "subject": "vocabulary",
        "level": "Beginner",
        "age_band": "6-10",
        "order_index": 2,
        "description": "Learn common color words and use them in short sentences.",
        "duration_minutes": 12,
        "xp_reward": 45,
        "content": {
            "explanation": "Describe objects using basic colors.",
            "examples": ["The sky is blue.", "My bag is red.", "The leaf is green."],
        },
    },
    {
        "code": "ab6-verbs-1",
        "title": "Action Verbs",
        "subject": "grammar",
        "level": "Beginner",
        "age_band": "6-10",
        "order_index": 3,
        "description": "Use simple present verbs in everyday sentences.",
        "duration_minutes": 12,
        "xp_reward": 45,
        "content": {
            "explanation": "Verbs show action. Use I/You/We/They + base verb.",
            "examples": ["I run fast.", "They play football.", "We read books."],
        },
    },
    {
        "code": "ab6-reading-1",
        "title": "Mini Story Time",
        "subject": "reading",
        "level": "Beginner",
        "age_band": "6-10",
        "order_index": 4,
        "description": "Read a short story and answer easy comprehension questions.",
        "duration_minutes": 14,
        "xp_reward": 50,
        "content": {
            "explanation": "Read sentence by sentence and find key words.",
            "examples": ["Tom has a red ball.", "He plays in the park.", "He is happy."],
        },
    },
    {
        "code": "ab6-sentence-1",
        "title": "Build Simple Sentences",
        "subject": "writing",
        "level": "Beginner",
        "age_band": "6-10",
        "order_index": 5,
        "description": "Arrange words to make complete sentences.",
        "duration_minutes": 12,
        "xp_reward": 45,
        "content": {
            "explanation": "A simple sentence needs a subject and a verb.",
            "examples": ["The cat sleeps.", "I like apples.", "My friend is kind."],
        },
    },
    {
        "code": "ab6-pronounce-1",
        "title": "Clear Sounds Practice",
        "subject": "listening",
        "level": "Beginner",
        "age_band": "6-10",
        "order_index": 6,
        "description": "Practice hearing and repeating common word sounds.",
        "duration_minutes": 10,
        "xp_reward": 40,
        "content": {
            "explanation": "Listen for beginning and ending sounds in words.",
            "examples": ["cat", "dog", "ship"],
        },
    },
    {
        "code": "ab11-intro-talk-1",
        "title": "Self-Introduction Plus",
        "subject": "speaking",
        "level": "Beginner",
        "age_band": "11-15",
        "order_index": 1,
        "description": "Introduce yourself with hobbies, school, and goals.",
        "duration_minutes": 12,
        "xp_reward": 50,
        "content": {
            "explanation": "Use 4-5 connected sentences and linking words.",
            "examples": ["My name is Sara and I am 12 years old.", "I enjoy drawing and basketball."],
        },
    },
    {
        "code": "ab11-tenses-1",
        "title": "Present vs Past Basics",
        "subject": "grammar",
        "level": "Beginner",
        "age_band": "11-15",
        "order_index": 2,
        "description": "Distinguish present and past tense in daily contexts.",
        "duration_minutes": 15,
        "xp_reward": 55,
        "content": {
            "explanation": "Use present for routines and past for finished actions.",
            "examples": ["I walk to school every day.", "Yesterday, I walked with my friend."],
        },
    },
    {
        "code": "ab11-vocab-school-1",
        "title": "School Life Vocabulary",
        "subject": "vocabulary",
        "level": "Beginner",
        "age_band": "11-15",
        "order_index": 3,
        "description": "Learn terms used in class discussions and assignments.",
        "duration_minutes": 12,
        "xp_reward": 50,
        "content": {
            "explanation": "Use new words in context, not in isolation.",
            "examples": ["deadline", "project", "presentation", "feedback"],
        },
    },
    {
        "code": "ab11-reading-1",
        "title": "Informational Reading",
        "subject": "reading",
        "level": "Intermediate",
        "age_band": "11-15",
        "order_index": 4,
        "description": "Read a short non-fiction paragraph and identify main idea.",
        "duration_minutes": 16,
        "xp_reward": 60,
        "content": {
            "explanation": "Find topic sentence and supporting details.",
            "examples": ["Underline the main idea.", "List two supporting facts."],
        },
    },
    {
        "code": "ab11-writing-1",
        "title": "Paragraph Builder",
        "subject": "writing",
        "level": "Intermediate",
        "age_band": "11-15",
        "order_index": 5,
        "description": "Write a short paragraph with topic and supporting ideas.",
        "duration_minutes": 18,
        "xp_reward": 65,
        "content": {
            "explanation": "Use transition words: first, next, finally.",
            "examples": ["My favorite hobby is...", "One reason is...", "In conclusion..."],
        },
    },
    {
        "code": "ab11-listen-1",
        "title": "Listening for Details",
        "subject": "listening",
        "level": "Intermediate",
        "age_band": "11-15",
        "order_index": 6,
        "description": "Listen to short dialogues and identify key details.",
        "duration_minutes": 14,
        "xp_reward": 55,
        "content": {
            "explanation": "Focus on names, times, and places.",
            "examples": ["Who is speaking?", "What time is the event?"],
        },
    },
    {
        "code": "ab16-interview-1",
        "title": "Interview Skills",
        "subject": "speaking",
        "level": "Intermediate",
        "age_band": "16-21",
        "order_index": 1,
        "description": "Answer common interview questions clearly and confidently.",
        "duration_minutes": 18,
        "xp_reward": 70,
        "content": {
            "explanation": "Structure answers with example and reflection.",
            "examples": ["Tell me about yourself.", "Describe a challenge you solved."],
        },
    },
    {
        "code": "ab16-grammar-1",
        "title": "Complex Sentences",
        "subject": "grammar",
        "level": "Intermediate",
        "age_band": "16-21",
        "order_index": 2,
        "description": "Use relative clauses and connectors for richer writing.",
        "duration_minutes": 20,
        "xp_reward": 75,
        "content": {
            "explanation": "Connect ideas with because, although, which, that.",
            "examples": ["The course that I joined was practical.", "Although it was hard, I improved."],
        },
    },
    {
        "code": "ab16-vocab-1",
        "title": "Academic Vocabulary Core",
        "subject": "vocabulary",
        "level": "Intermediate",
        "age_band": "16-21",
        "order_index": 3,
        "description": "Build vocabulary for essays, reports, and presentations.",
        "duration_minutes": 16,
        "xp_reward": 65,
        "content": {
            "explanation": "Use precise words and collocations.",
            "examples": ["analyze data", "draw a conclusion", "conduct research"],
        },
    },
    {
        "code": "ab16-reading-1",
        "title": "Critical Reading",
        "subject": "reading",
        "level": "Advanced",
        "age_band": "16-21",
        "order_index": 4,
        "description": "Identify argument structure, claim, and evidence in short texts.",
        "duration_minutes": 22,
        "xp_reward": 80,
        "content": {
            "explanation": "Separate opinion from evidence and evaluate logic.",
            "examples": ["What is the claim?", "Which evidence supports it?"],
        },
    },
    {
        "code": "ab16-writing-1",
        "title": "Argument Paragraph",
        "subject": "writing",
        "level": "Advanced",
        "age_band": "16-21",
        "order_index": 5,
        "description": "Write a persuasive paragraph with evidence and conclusion.",
        "duration_minutes": 24,
        "xp_reward": 85,
        "content": {
            "explanation": "State your position, give evidence, then conclude.",
            "examples": ["In my view...", "For example...", "Therefore..."],
        },
    },
    {
        "code": "ab16-listen-1",
        "title": "Lecture Listening",
        "subject": "listening",
        "level": "Advanced",
        "age_band": "16-21",
        "order_index": 6,
        "description": "Take notes from short lecture-style audio and summarize key points.",
        "duration_minutes": 20,
        "xp_reward": 75,
        "content": {
            "explanation": "Capture main points, examples, and conclusions.",
            "examples": ["Main topic", "Key example", "Final takeaway"],
        },
    },
]


def seed_lessons_if_empty(db: Session) -> None:
    existing = db.query(Lesson).count()
    if existing > 0:
        return

    for lesson in LESSON_SEED:
        db.add(
            Lesson(
                code=lesson["code"],
                title=lesson["title"],
                subject=lesson["subject"],
                level=lesson["level"],
                age_band=lesson["age_band"],
                order_index=lesson["order_index"],
                description=lesson["description"],
                duration_minutes=lesson["duration_minutes"],
                xp_reward=lesson["xp_reward"],
                content_json=json.dumps(lesson["content"]),
                is_published=1,
            )
        )

    db.commit()
